/*
 * SecuManga Service
 * Code-Beispiel zum Buch Patterns Kompakt, Verlag Springer Vieweg
 * Copyright 2014 Karl Eilebrecht
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package de.calamanari.pk.gateway.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.6 in JDK 6 Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "SecuMangaService", targetNamespace = "http://gateway.pk.calamanari.de/",
        wsdlLocation = "http://localhost:8091/SecuMangaWebService?wsdl")
public class SecuMangaService extends Service {

    /**
     * location
     */
    private static final URL SECUMANGASERVICE_WSDL_LOCATION;
    
    /**
     * logger
     */
    private static final Logger LOGGER = Logger.getLogger(de.calamanari.pk.gateway.client.SecuMangaService.class
            .getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = de.calamanari.pk.gateway.client.SecuMangaService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8091/SecuMangaWebService?wsdl");
        }
        catch (MalformedURLException e) {
            LOGGER.warning("Failed to create URL for the wsdl Location: "
                    + "'http://localhost:8091/SecuMangaWebService?wsdl', retrying as a local file");
            LOGGER.warning(e.getMessage());
        }
        SECUMANGASERVICE_WSDL_LOCATION = url;
    }

    /**
     * Creates service from url and name
     * @param wsdlLocation url
     * @param serviceName name of service
     */
    public SecuMangaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * Creates service with default settings
     */
    public SecuMangaService() {
        super(SECUMANGASERVICE_WSDL_LOCATION, new QName("http://gateway.pk.calamanari.de/", "SecuMangaService"));
    }

    /**
     * 
     * @return returns SecuMangaWebService
     */
    @WebEndpoint(name = "SecuMangaWebServicePort")
    public SecuMangaWebService getSecuMangaWebServicePort() {
        return super.getPort(new QName("http://gateway.pk.calamanari.de/", "SecuMangaWebServicePort"),
                SecuMangaWebService.class);
    }

    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features
     *            not in the <code>features</code> parameter will have their default values.
     * @return returns SecuMangaWebService
     */
    @WebEndpoint(name = "SecuMangaWebServicePort")
    public SecuMangaWebService getSecuMangaWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gateway.pk.calamanari.de/", "SecuMangaWebServicePort"),
                SecuMangaWebService.class, features);
    }

}
